name: aws_s3_upload
description: A simple, convenient package for uploading to S3.
version: 1.5.1
homepage: https://github.com/Serdnad/aws_s3_upload

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  amazon_cognito_identity_dart_2: ^3.5.0
  http: ^1.1.0
  path: ^1.8.0
  recase: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter: null
